root: true
parser: babel-eslint
parserOptions:
  sourceType: module
extends: standard
env:
  browser: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
